-- liquibase formatted sql
CREATE TABLE "tag" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "value" VARCHAR NOT NULL,
  "author" BIGINT NOT NULL,
  "created_at" TIMESTAMP WITH TIME ZONE DEFAULT NOW() NOT NULL,
  CONSTRAINT "tag_pkey" PRIMARY KEY ("id"),
  CONSTRAINT "unique_value" UNIQUE ("value", "author"),
  CONSTRAINT "tag_author_fkey" FOREIGN KEY ("author") REFERENCES "user" ("id") ON UPDATE CASCADE ON DELETE RESTRICT
);
--rollback DROP TABLE "tag";
